### ISSUE TITLE
Our document types config is inconsistent

### ISSUE THREAD

**Issue by benthorner** [alphagov/content-publisher#1676]
The [document_types.yml](https://github.com/alphagov/content-publisher/blob/566d2bff24ca13877a94eb67776e036a067b0b4e/config/document_types.yml) file is pretty inconsistent: it's a mixture of English (e.g. `hint_govspeak`), flags (e.g. `images: true`), abstractions (e.g. `contents: [...]`) and metadata (e.g. `path_prefix: ...`). We're currently doing work to mitigate some of this inconsistency, by [extracting bits of English](https://trello.com/c/AuzTdQVt/1100-use-i18n-to-manage-copy-for-each-document-type) and [using a more fine-grained type system to support  "flexible fields"](https://trello.com/c/u9kRKVsX/1324-extract-title-and-summary-into-classes-views-and-config).

After this work, the `document_types.yml` file should look something like this:

```
- id: news_story
  path_prefix: /government/news
  images: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - id: primary_publishing_organisation
      type: single_tag
      document_type: organisation
    - id: organisations
      type: multi_tag
      document_type: organisation
    - id: role_appointments
      type: multi_tag
      document_type: role_appointment
    - id: topical_events
      type: multi_tag
      document_type: topical_event
    - id: world_locations
      type: multi_tag
      document_type: world_location
```

Some of the obvious next steps are tidying-up tag fields and metadata. This will make it easier to talk about (and implement) further iterations to the config file.

```
- id: news_story
  images: true
  metadata:
    schema_name: news_article
    rendering_app: government-frontend
    path_prefix: /government/news
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - primary_publishing_organisation
    - organisations
    - role_appointments
    - topical_events
    - world_locations
```

Although there is only one remaining anomaly (`images: true`) in the above example, as part of the work on attachments, we expect to need additional config:

   - Config to optionally switch on the "attachment list" feature, where a document can have an ordered/curated/featured list of file/external/HTML attachments.
   - Config to modify the existing "file attachments" feature, where a user can only insert inline/link snippets into their body content, for Publication document types.
   - Config to modify the upcoming external/HTML attachment features, so that neither of them is available for existing (news) document types.
   - Config to modify the available fields for the "file attachments" feature, so the user can also specify metadata like ISBN, as well official document metadata.

While we can use "flexible fields" to support the latter, our single example of switching feature behaviours (`images: true`) doesn't scale well:

   - The flag is vague and pollutes the top level of the config
   - It's unclear how to specify lower-level switches e.g. block snippets "off"

**Comment by benthorner** [comment]
As a potential solution, we could iterate the `tags` and `contents` abstractions into a new concept: a "feature". Each "feature" may have "fields" and "flags":

```
- id: policy_paper
  metadata:
    schema_name: publication
    rendering_app: government-frontend
    path_prefix: /government/publications
  features:
    [topics: true] # defaulted in code
    contents:
      fields:
        - title_and_base_path
        - summary
        - body
    tags:
      fields:
        - primary_publishing_organisation
        - organisations
        - role_appointments
        - topical_events
        - world_locations
    attachments:
      flags:
        with_document_level_list: true
        with_external_attachments: true
        with_html_attachments: true
    file_attachments:
      flags:
        [with_block_snippets: true] # for news
      fields:
        - title
        - isbn
        - official_document_selector
    images:
      flags:
        - with_lead_image: true
```

The exact config still depends on the functionality we agree for attachments, but it's worth talking about some of the generic properties we may find desirable:

   - All features have a single, generic interface of "fields" and "flags" to express their behaviour; this prevents inconsistency by having lots of different sub-models and attributes.
   - The feature naming can be coarse (`images`) or fine (`edit_images` + `lead_images`), depending on the level of specificity and what makes sense in terms of features vs. flags.
   - We need only specify the config that is necessary: everything is `false` by default (except `topics`), and we should still avoid enabling config where it's not required e.g. image fields.
   - We can use "flags" to specify lower-level behaviours of a feature, such as block snippets - the equivalent feature would be verbose e.g. `insert_file_attachment_block_snippets: true`.
   - The presence of a feature key is a switch e.g. `has_feature?(:attachments)`, which also has meaning for "sub-features" e.g. `has_feature?(:attachments, :with_document_level_list)`.
   - The use of a "fields" key gives meaning to the list it contains, and allows us to extend the "feature" concept with other things (like "flags") without too much work.

**Comment by kevindew** [comment]
Thanks for putting this together @benthorner , looks like a lot of thought went into it 👍 

I quite like the idea of the features section. The naming seems a little strange because a bunch of aspects aren't really features - for example we expect everything to have content - so that doesn't feel quite right. But it's not a dealbreaker for me.

If we are to have a concept of a feature, what actually is it that is represents? is there a class?

Another thing I'm wondering is about is how we handle each publication type? Will we be having using YAML imports or repeating things? Just thinking about the effects of duplication.

Having had a think about the flags and fields approach I've concluded that I think this is actually too rigid and shouldn't be applied to every configurable thing. Some examples of thoughts:

- Not everything should have or makes sense with fields (for example, topics)
- Some features (for example, images) have fields but they should always be the same so shouldn't be configurable
- We hope to split content to allow multiple fields over different views for publications
- File attachments (as far as I'm aware) seem to have split fields title on one view more on the next

Is there a less rigid approach we can take? 

Sorry to have a bit of a u-turn but I do find myself wondering if it's maybe a bad call to make the fields configurable for attachments to support the extra fields for publications and consultations. It seems unlikely these will ever be mixed and matched and may risk leading us down a road of highly configurable things that are only used in very prescribed ways. I worry a bit that this actually leads to us having to create a second variety of fields that have slightly different responsibilities to the ones we expect for content (these would have requirements but not be part of Publishing API payload for instance). There might well end up being a YAGNI aspect of making them configurable.

Happy to have a chat to explain my thoughts more if you like and/or do brainstorming on this.

**Comment by benthorner** [comment]
Thanks for taking a look @kevindew. Your point about splitting content over several screens was particularly compelling. I think it would help to start by listing some of the things we want:

   - We want to move away from top-level config for `contents`, `tags`, `images` and `topics`, since they have things in common with each other, but not `metadata`.
   - We want to be able to represent an ordered list of (flexible) fields for `contents` and `tags`.
   - We want to to represent switching behaviours, either for whole features (e.g. external attachments), or aspects of them (e.g. lead images). These switches will be used by assertions, views, API payload generators, requirements checkers.
   - We want at least some consistency in the way config for `contents`, `images`, etc. is modelled i.e. we should be able to refer to them in the same way.
   - We *don't* want to force config where it's not necessary

I agree with your point about attachment fields: although I do believe they would be used in a similar way, it might be simpler to implement the difference in behaviour with a switch. An interesting issue here is around requirements checking for the two variants of a file attachment. With fields, it would be relatively simple, as each field is responsible for its own checks; but we may also be able to implement the equivalent behaviour with an `if` around a bunch of Publication-specific checks.

> Will we be having using YAML imports or repeating things?

I'm assuming you meant anchors/aliases - yes, we should consider those.

> If we are to have a concept of a feature, what actually is it that is represents? is there a class?

I hope so. What exactly depends on the variety of config.

This where we may want to talk in person, but I'll try and outline my latest ideas. Having learnt and thought more about our design for attachments, the "all-in-one" workflow is going to be quite separate from the workflow for file attachments. Here's the latest config.

```
- id: policy_paper
  metadata:
    schema_name: publication
    rendering_app: government-frontend
    path_prefix: /government/publications
  features:
    [topics: true] # defaulted in code
    contents:
      fields: [...]
    tags:
      fields: [...]
    attachments:
      traits:
        [- inline_file_only] # for news
        - document_level
    images: true
      [traits:
        - with_lead_image] # for news
```

One thing I'm trying to avoid is having a set of alternative conditions to assert against e.g. file attachment download is available in all cases. At the same time, I think we should avoid having switches to "switch things off", as that could get confusing. Having incompatible traits is at least something we're used to in tests. This config suggests a common `DocumentType::Feature` class:

   - `traits` are generic enough that any "feature" could have them.
   - `fields` are specific to two features, so we could subclass here.
   - A "feature" may enabled without config e.g. `topics`, `images`.

The suggested methods above - `has_feature?(:topics)` and `has_feature?(:images, :with_lead_image)` - still make sense. While I agree `contents` is never disabled, it also doesn't make sense unless we specify some fields. This feels like the sort of thing we could cover with data integrity tests around the config.
